#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "-----------------------------------"
echo "Linting and building your code..."
echo "-----------------------------------"

pnpm lint && pnpm build:esm

echo "-----------------------------------"
echo "You can now push your code..."
