name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.2, 18.19.0, 20.10.0]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: install, lint, build
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm build:esm
        env:
          CI: true
          # API_BASE_URL: ${{ secrets.API_BASE_URL }}
          # API_KEY: ${{ secrets.API_KEY }}s
