name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.2, 18.19.0, 20.10.0]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install, lint, build
        run: |
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm build:esm
        env:
          CI: true
          # API_BASE_URL: ${{ secrets.API_BASE_URL }}
          # API_CUSTOM_HEADERS: ${{ secrets.API_CUSTOM_HEADERS }}

  publish:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public  
